# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

CONFIG(debug, debug|release){
		TARGET = plugin_telecontrold
} else {
	TARGET = plugin_telecontrol
}

include(../../plugin_sln.pri)
	QT += 
	DEFINES +=
	include(plugin_telecontrol.pri)

