# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

HEADERS += ./plugin_telecontrol.h \
    ./view_plugin_telecontrol.h
SOURCES += ./plugin_telecontrol.cpp \
    ./view_plugin_telecontrol.cpp
FORMS += ./view_plugin_telecontrol.ui 
RESOURCES += plugin_telecontrol.qrc 

