# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

CONFIG(debug, debug|release){
		TARGET = plugin_demo2d
} else {
	TARGET = plugin_demo2
}

include(../../plugin_sln.pri)
	QT += 
	DEFINES +=
	include(plugin_demo2.pri)

