# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

HEADERS += ./plugin_demo2.h \
    ./view_plugin_demo2.h
SOURCES += ./plugin_demo2.cpp \
    ./view_plugin_demo2.cpp
FORMS += ./view_plugin_demo2.ui 
RESOURCES += plugin_demo2.qrc 

