# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

HEADERS += ./plugin_drawer.h \
    ./view_plugin_drawer.h
SOURCES += ./plugin_drawer.cpp \
    ./view_plugin_drawer.cpp
FORMS += ./view_plugin_drawer.ui 
RESOURCES += plugin_drawer.qrc 

