# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

CONFIG(debug, debug|release){
		TARGET = plugin_drawerd
} else {
	TARGET = plugin_drawer
}

include(../../plugin_sln.pri)
	QT += 
	DEFINES +=
	include(plugin_drawer.pri)

