# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

CONFIG(debug, debug|release){
		TARGET = plugin_modbus_rtud
} else {
	TARGET = plugin_modbus_rtu
}

include(../../plugin_sln.pri)
	QT += 
	DEFINES +=
	include(plugin_modbus_rtu.pri)

