# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

HEADERS += ./plugin_modbus_rtu.h \
    ./view_plugin_modbus_rtu.h
SOURCES += ./plugin_modbus_rtu.cpp \
    ./view_plugin_modbus_rtu.cpp
FORMS += ./view_plugin_modbus_rtu.ui 
RESOURCES += plugin_modbus_rtu.qrc 

