# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./sizehandle.h \
    ./skdraw.h \
    ./wndadd.h \
    ./rulebar.h \
    ./commands.h \
    ./propertyeditor.h \
    ./shaprelate.h \
    ./db.h \
    ./dbpic.h \
    ./seldb.h \
    ./selfun.h \
    ./drawtool.h \
    ./drawscene.h \
    ./drawview.h \
    ./drawobj.h \
    ./qtpropertybrowser/qtbuttonpropertybrowser.h \
    ./qtpropertybrowser/qteditorfactory.h \
    ./qtpropertybrowser/qtgroupboxpropertybrowser.h \
    ./qtpropertybrowser/qtpropertybrowser.h \
    ./qtpropertybrowser/qtpropertybrowserutils_p.h \
    ./qtpropertybrowser/qtpropertymanager.h \
    ./qtpropertybrowser/qttreepropertybrowser.h \
    ./qtpropertybrowser/qtvariantproperty.h
SOURCES += ./commands.cpp \
    ./db.cpp \
    ./dbpic.cpp \
    ./drawobj.cpp \
    ./drawscene.cpp \
    ./drawtool.cpp \
    ./drawview.cpp \
    ./main.cpp \
    ./propertyeditor.cpp \
    ./rulebar.cpp \
    ./seldb.cpp \
    ./selfun.cpp \
    ./shaprelate.cpp \
    ./sizehandle.cpp \
    ./skdraw.cpp \
    ./wndadd.cpp \
    ./qtpropertybrowser/qtbuttonpropertybrowser.cpp \
    ./qtpropertybrowser/qteditorfactory.cpp \
    ./qtpropertybrowser/qtgroupboxpropertybrowser.cpp \
    ./qtpropertybrowser/qtpropertybrowser.cpp \
    ./qtpropertybrowser/qtpropertybrowserutils.cpp \
    ./qtpropertybrowser/qtpropertymanager.cpp \
    ./qtpropertybrowser/qttreepropertybrowser.cpp \
    ./qtpropertybrowser/qtvariantproperty.cpp
FORMS += ./skdraw.ui \
    ./shaprelate.ui \
    ./seldb.ui \
    ./wndadd.ui \
    ./dbpic.ui \
    ./selfun.ui
RESOURCES += skdraw.qrc \
    qtpropertybrowser/qtpropertybrowser.qrc
