# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
CONFIG(debug, debug|release){
  TARGET = plugin_scl_importd
} else {
  TARGET = plugin_scl_import
}

include(../../plugin_sln.pri)
QT += 
DEFINES +=
include(plugin_scl_import.pri)

unix {
	INCLUDEPATH += ../../..
}