# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

CONFIG(debug, debug|release){
		TARGET = plugin_demo1d
} else {
	TARGET = plugin_demo1
}

include(../../plugin_sln.pri)
	QT += 
	DEFINES +=
	include(plugin_demo1.pri)

