# ----------------------------------------------------
# This file is generated by the SspAssist(skt001@163.com).
# ------------------------------------------------------

HEADERS += ./plugin_demo1.h \
    ./view_plugin_demo1.h
SOURCES += ./plugin_demo1.cpp \
    ./view_plugin_demo1.cpp
FORMS += ./view_plugin_demo1.ui 
RESOURCES += plugin_demo1.qrc 

